# fly.toml app configuration file generated for snowy-violet-6688 on 2023-07-28T11:21:29+01:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "snowy-violet-6688"
primary_region = "lhr"

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]
